/**
 * Generate the HTML viewer bridge assets that ship in the npm package.
 *
 * `components/html-viewer/bridge-script.ts` stays the source of truth: the
 * Plannotator CLI and the Pi extension import its string exports under Bun,
 * and the srcdoc path inlines `BRIDGE_SCRIPT` by default. This script derives
 * two files from it at `prepack` (both gitignored, both deterministic):
 *
 * - `bridge-script.asset.js`: the bridge IIFE, byte-for-byte `BRIDGE_SCRIPT`,
 *   for hosts that serve it as a hashed static asset and pass its URL to
 *   `HtmlViewer` as `bridgeScriptUrl` (a Vite `?url` import of the package
 *   subpath). The `.asset.js` name is deliberate: a plain `bridge-script.js`
 *   beside `bridge-script.ts` would be picked FIRST by Vite's extension probe
 *   for the package's own `./bridge-script` imports (`.js` precedes `.ts` in
 *   `resolve.extensions`), which would break every consumer build.
 * - `bridge-script.lite.ts`: an alias target with the same CSS, protocol
 *   version and live bootstrap but `BRIDGE_SCRIPT = ""`, so a host on the URL
 *   path can point its bundler's `./bridge-script` resolution at it and drop
 *   the 185 KB literal from its viewer chunk. Optional; without the alias the
 *   URL path still works, the literal is merely carried unused.
 *
 * `bridgeAsset.test.ts` regenerates both into a temp dir and compares them to
 * the source exports, so a drift between the generator and the module fails
 * the suite rather than shipping.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ANNOTATION_HIGHLIGHT_CSS,
  BRIDGE_PROTOCOL_VERSION,
  BRIDGE_SCRIPT,
  LIVE_BRIDGE_BOOTSTRAP,
} from "../components/html-viewer/bridge-script";

export const BRIDGE_ASSET_FILENAME = "bridge-script.asset.js";
export const BRIDGE_LITE_FILENAME = "bridge-script.lite.ts";

/** Where the assets live in the package (beside their source module). */
export const BRIDGE_ASSET_DIR = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../components/html-viewer",
);

/** The runnable asset: exactly the inline string, no banner, no trailer. */
export function renderBridgeAsset(): string {
  return BRIDGE_SCRIPT;
}

/** The alias module: every export of `./bridge-script` except the literal. */
export function renderBridgeLiteModule(): string {
  return [
    "// @generated by scripts/build-bridge-assets.ts from ./bridge-script.ts. DO NOT EDIT.",
    "// Alias target for hosts on the HtmlViewer `bridgeScriptUrl` path: the same",
    "// annotation CSS, protocol version and live bootstrap as ./bridge-script, with",
    "// the inline bridge literal stubbed out so a bundler drops it from the viewer",
    "// chunk. Rendering an HtmlViewer WITHOUT bridgeScriptUrl under this alias throws.",
    `export const ANNOTATION_HIGHLIGHT_CSS = ${JSON.stringify(ANNOTATION_HIGHLIGHT_CSS)};`,
    `export const BRIDGE_PROTOCOL_VERSION = ${JSON.stringify(BRIDGE_PROTOCOL_VERSION)};`,
    'export const BRIDGE_SCRIPT = "";',
    `export const LIVE_BRIDGE_BOOTSTRAP = ${JSON.stringify(LIVE_BRIDGE_BOOTSTRAP)};`,
    "",
  ].join("\n");
}

/** Write both files into `dir`; returns the paths written. */
export function writeBridgeAssets(dir: string = BRIDGE_ASSET_DIR): string[] {
  mkdirSync(dir, { recursive: true });
  const asset = join(dir, BRIDGE_ASSET_FILENAME);
  const lite = join(dir, BRIDGE_LITE_FILENAME);
  writeFileSync(asset, renderBridgeAsset(), "utf8");
  writeFileSync(lite, renderBridgeLiteModule(), "utf8");
  return [asset, lite];
}

if (import.meta.main) {
  for (const path of writeBridgeAssets()) {
    console.log(`wrote ${path}`);
  }
}
